/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinRoomResponseChatHistoryInner
 */
export interface JoinRoomResponseChatHistoryInner {
    /**
     * 
     * @type {string}
     * @memberof JoinRoomResponseChatHistoryInner
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof JoinRoomResponseChatHistoryInner
     */
    sender?: string;
}

/**
 * Check if a given object implements the JoinRoomResponseChatHistoryInner interface.
 */
export function instanceOfJoinRoomResponseChatHistoryInner(value: object): value is JoinRoomResponseChatHistoryInner {
    return true;
}

export function JoinRoomResponseChatHistoryInnerFromJSON(json: any): JoinRoomResponseChatHistoryInner {
    return JoinRoomResponseChatHistoryInnerFromJSONTyped(json, false);
}

export function JoinRoomResponseChatHistoryInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinRoomResponseChatHistoryInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'sender': json['sender'] == null ? undefined : json['sender'],
    };
}

  export function JoinRoomResponseChatHistoryInnerToJSON(json: any): JoinRoomResponseChatHistoryInner {
      return JoinRoomResponseChatHistoryInnerToJSONTyped(json, false);
  }

  export function JoinRoomResponseChatHistoryInnerToJSONTyped(value?: JoinRoomResponseChatHistoryInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'sender': value['sender'],
    };
}

