/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UIPhase = {
    Waiting: 'WAITING',
    Playing: 'PLAYING',
    End: 'END'
} as const;
export type UIPhase = typeof UIPhase[keyof typeof UIPhase];


export function instanceOfUIPhase(value: any): boolean {
    for (const key in UIPhase) {
        if (Object.prototype.hasOwnProperty.call(UIPhase, key)) {
            if (UIPhase[key as keyof typeof UIPhase] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UIPhaseFromJSON(json: any): UIPhase {
    return UIPhaseFromJSONTyped(json, false);
}

export function UIPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIPhase {
    return json as UIPhase;
}

export function UIPhaseToJSON(value?: UIPhase | null): any {
    return value as any;
}

export function UIPhaseToJSONTyped(value: any, ignoreDiscriminator: boolean): UIPhase {
    return value as UIPhase;
}

